version: '3'
services:
  nsqlookupd-1:
    container_name: nsqlookupd-1
    image: nsqio/nsq:v1.2.0
    entrypoint: /nsqlookupd
    networks:
      - nsq-net

  nsqlookupd-2:
    container_name: nsqlookupd-2
    image: nsqio/nsq:v1.2.0
    entrypoint: /nsqlookupd
    networks:
      - nsq-net

  nsqlookupd-3:
    container_name: nsqlookupd-3
    image: nsqio/nsq:v1.2.0
    entrypoint: /nsqlookupd
    networks:
      - nsq-net

  nsqd-1:
    container_name: nsqd-1
    image: nsqio/nsq:v1.2.0
    entrypoint: /nsqd
    command:
      - --lookupd-tcp-address=nsqlookupd-1:4160
      - --lookupd-tcp-address=nsqlookupd-2:4160
      - --lookupd-tcp-address=nsqlookupd-3:4160
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3
    networks:
      - nsq-net

  nsqd-2:
    container_name: nsqd-2
    image: nsqio/nsq:v1.2.0
    entrypoint: /nsqd
    command:
      - --lookupd-tcp-address=nsqlookupd-1:4160
      - --lookupd-tcp-address=nsqlookupd-2:4160
      - --lookupd-tcp-address=nsqlookupd-3:4160
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3
    networks:
      - nsq-net

  nsqd-3:
    container_name: nsqd-3
    image: nsqio/nsq:v1.2.0
    entrypoint: /nsqd
    command:
      - --lookupd-tcp-address=nsqlookupd-1:4160
      - --lookupd-tcp-address=nsqlookupd-2:4160
      - --lookupd-tcp-address=nsqlookupd-3:4160
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3
    networks:
      - nsq-net

  nsqadmin:
    image: nsqio/nsq:v1.2.0
    entrypoint: /nsqadmin
    command:
      - --lookupd-http-address=nsqlookupd-1:4161
      - --lookupd-http-address=nsqlookupd-2:4161
      - --lookupd-http-address=nsqlookupd-3:4161
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3
    ports:
      - 4171:4171
    networks:
      - nsq-net

  consumer1:
    container_name: consumer1
    image: consumer:latest
    entrypoint: /consumer
    environment:
      - ID=1
      - LOOKUPD_SERVERS=nsqlookupd-1:4161 nsqlookupd-2:4161 nsqlookupd-3:4161
      - TOPIC=test_topic
      - CHANNEL=test_channel
    networks:
      - nsq-net
    depends_on:
      - nsqd-1
      - nsqd-2
      - nsqd-3
      - producer1

  producer1:
    container_name: producer1
    image: producer:latest
    entrypoint: /producer
    environment:
      - ID=1
      - TOPIC=test_topic
      - CHANNEL=test_channel
      - LOOP_INTERVAL=1s
      - NSQD_SERVER=nsqd-1:4150
    networks:
      - nsq-net
    depends_on:
      - nsqd-1
      - nsqd-2
      - nsqd-3

networks:
  nsq-net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.126.0/24